export enum Ugel{
    DRE_MOQUEGUA = 'DRE MOQUEGUA',
    UGEL_GENERAL_SANCHEZ_CERRO = 'UGEL GENERAL SANCHEZ CERRO',
    UGEL_MARISCAL_NIETO = 'UGEL MARISCAL NIETO',
    UGEL_SAN_IGNACIO_DE_LOYOLA_ICHUNA = 'UGEL SAN IGNACIO DE LOYOLA-ICHUÑA',
    UGEL_ILO = 'UGEL ILO',
}